#!/bin/sh
#
#   Copyright (c) 2012 Tzeng, Yi-Feng <yftzeng@gmail.com>.
#
#   (The MIT License)
#
#   This file is part of phpWowExtension.
#
#   Permission is hereby granted, free of charge, to any person obtaining
#   a copy of this software and associated documentation files (the
#   "Software"), to deal in the Software without restriction, including
#   without limitation the rights to use, copy, modify, merge, publish,
#   distribute, sublicense, and/or sell copies of the Software, and to
#   permit persons to whom the Software is furnished to do so, subject to
#   the following conditions:
#
#   The above copyright notice and this permission notice shall be
#   included in all copies or substantial portions of the Software.
#
#   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
#   LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
#   OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
#   WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

usage() {
    echo "Usage: $(basename $0) extname=EXTENSION_NAME"
    exit
}

skeleton() {
    \cp -f "../skeleton/skeleton.h" "../ext/$extname/$extname.h"
    sed -i "s/skeleton/$extname/g" "../ext/$extname/$extname.h"
    sed -i "s/Skeleton/$extname_first_letter_capitilise/g" "../ext/$extname/$extname.h"

    \cp -f "../skeleton/skeleton.c" "../ext/$extname/$extname.c"
    sed -i "s/skeleton/$extname/g" "../ext/$extname/$extname.c"
    sed -i "s/Skeleton/$extname_first_letter_capitilise/g" "../ext/$extname/$extname.c"
    sed -i "s/SKELETON/$extname_all_letter_capitilise/g" "../ext/$extname/$extname.c"

    \cp -f "../skeleton/test.c" "../ext/$extname/."
    sed -i "s/skeleton/$extname/g" "../ext/$extname/test.c"
    sed -i "s/Skeleton/$extname_first_letter_capitilise/g" "../ext/$extname/test.c"

    \cp -rpf "../skeleton/tests" "../ext/$extname/."
    sed -i "s/Skeleton/$extname_first_letter_capitilise/g" "../ext/$extname/tests/test.php"
}

finalize() {
    # config.m4
    sed -i "s/PHP_NEW_EXTENSION.*/PHP_NEW_EXTENSION(phalcon,\n\n  phalcon.c \\\\\n  kernel\/array.c \\\\\n  kernel\/assert.c \\\\\n  kernel\/concat.c \\\\\n  kernel\/debug.c \\\\\n  kernel\/exception.c \\\\\n  kernel\/fcall.c \\\\\n  kernel\/main.c \\\\\n  kernel\/memory.c \\\\\n  kernel\/object.c \\\\\n  kernel\/operators.c \\\\\n  kernel\/output.c \\\\\n  kernel\/require.c \\\\\n  test.c,\n\n  \$ext_shared)/g" "../ext/$extname/config.m4"
    sed -i "s/phalcon/$extname/g" "../ext/$extname/config.m4"
    sed -i "s/Phalcon/$extname_first_letter_capitilise/g" "../ext/$extname/config.m4"
    sed -i "s/PHALCON/$extname_all_letter_capitilise/g" "../ext/$extname/config.m4"
    sed -i "s/\ [Ff]ramework//g" "../ext/$extname/config.m4"

    # php_phalcon.h
    sed -i "s/PHP_PHALCON_EXTNAME\ .*/PHP_PHALCON_EXTNAME\ \"$extname\"/g" "../ext/$extname/php_phalcon.h"
    sed -i "s/(phalcon/($extname/g" "../ext/$extname/php_phalcon.h"
    sed -i "s/zend_phalcon_globals/zend_$extname_globals/g" "../ext/$extname/php_phalcon.h"
    sed -i "s/phalcon_module_entry/$extname_module_entry/g" "../ext/$extname/php_phalcon.h"
    sed -i "s/phpext_phalcon_ptr/phpext_$extname_ptr/g" "../ext/$extname/php_phalcon.h"

    # kernel/main.h
    sed -i "s/zend_phalcon_globals/zend_${extname}_globals/g" "../ext/$extname/kernel/main.h"
    sed -i "s/zend_phalcon_globals/zend_${extname}_globals/g" "../ext/$extname/kernel/main.c"

    # kernel/concat.c
    sed -i "s/^\#include\ \"phalcon\.h\"$//" "../ext/$extname/kernel/concat.c"

    echo "Successful! Generate $extname in ext/$extname"
}

if test -z "$extname" ; then
    usage
fi

if test -d "../ext/$extname" ; then
    echo "Extenstion '$extname' already exists."
    exit
fi

extname_first_letter_capitilise=$(echo "$extname" | sed -e 's/^./\U&\E/')
extname_all_letter_capitilise=$(echo "$extname" | tr '[:lower:]' '[:upper:]')

mkdir -p "../ext/$extname" &&
    \cp -rpf ../cphalcon/. "../ext/$extname/." &&
    skeleton &&
    finalize
