#!/bin/sh
#
#   Copyright (c) 2012 Tzeng, Yi-Feng <yftzeng@gmail.com>.
#
#   (The MIT License)
#
#   This file is part of phpWowExtension.
#
#   Permission is hereby granted, free of charge, to any person obtaining
#   a copy of this software and associated documentation files (the
#   "Software"), to deal in the Software without restriction, including
#   without limitation the rights to use, copy, modify, merge, publish,
#   distribute, sublicense, and/or sell copies of the Software, and to
#   permit persons to whom the Software is furnished to do so, subject to
#   the following conditions:
#
#   The above copyright notice and this permission notice shall be
#   included in all copies or substantial portions of the Software.
#
#   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
#   LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
#   OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
#   WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

upstream_check() {
    if [ -d "cphalcon" ] ; then cd cphalcon && git pull && cd - > /dev/null 2>&1 ; else git clone --depth 1 https://github.com/phalcon/cphalcon.git ; fi
}

copy_phalcon_kernel_files() {
    \cp -f cphalcon/build/config.m4 cphalcon/build/php_phalcon.h ../cphalcon/. && ls &&
    \cp -rpf cphalcon/ext/kernel ../cphalcon/.
}

mkdir -p ../build &&
    cd ../build &&
    upstream_check &&
    copy_phalcon_kernel_files
